default:
  - preproccess: &preproccess
      script: tasks/preproccess.py
      arguments: 
        input_file: data/dummy.data
        nr_images: 500
        filters: True
  - training: &training
      script: tasks/train.py
  - validation: &validation
      script: tasks/validate.py
      arguments: 
        input_file: data/dummy.data
  - deployment: &deployment
      script: tasks/deploy.py

steps:
  - <<: *preproccess
  - <<: *training
  - <<: *validation
  - <<: *deployment
