cron:
  day_of_week: thu
  hour: '*'
  minute: '*'
  second: '*/10'

configs:
  - preproccess: &preproccess
        - script: tasks/preproccess.py
          options:
            input_file: data/dummy.data
          arguments:
            nr_images: 500
            filters: true
  - training: &training
      - script: tasks/train.py
  - validation: &validation
      - script: tasks/validate.py
        arguments:
          input_file: data/dummy.data
  - deployment: &deployment
      - script: tasks/deploy.py

steps:
  - <<: *preproccess
  - <<: *training
  - <<: *validation
  - <<: *deployment
