# config.yaml

config:
  - data_processing: &preproccess
      script: /Users/leanderlauenburg/Code/crude-link/tasks/preproccess.py
      arguments: 
        data_dir: /Users/leanderlauenburg/Code/crude-link/data/dummy.data
        nr_images: 500
        filters: True
  - training: &training
      script: /Users/leanderlauenburg/Code/crude-link/tasks/train.py
  - validation: &validation
      script: /Users/leanderlauenburg/Code/crude-link/tasks/validate.py
      arguments: 
        data_dir: /Users/leanderlauenburg/Code/crude-link/data/dummy.data
  - deployment: &deployment
      script: /Users/leanderlauenburg/Code/crude-link/tasks/deploy.py

steps:
  - <<: *preproccess
  - <<: *training
  - <<: *validation
  - <<: *deployment
