cron:
  day_of_week: thu
  hour: '*'
  minute: '*'
  second: '*/10'

configs:
  - preprocess: &preprocess
        - script: tasks/preprocess.py
          arguments:
            - "--input_file data/dummy.data"
            - "nr_images=500"
            - "filter=true"
  - training: &training
      - script: tasks/train.py
  - validation: &validation
      - script: tasks/validate.py
        arguments:
          - "--input_file data/dummy.data --forty_two 42"
  - deployment: &deployment
      - script: tasks/deploy.py

steps:
  - <<: *preprocess
  - <<: *training
  - <<: *validation
  - <<: *deployment